name = "financier-backend"
compatibility_date = "2025-01-28"
compatibility_flags = [ "nodejs_compat" ]
main = "./src/index.ts"
preview_urls = false
workers_dev = false

[observability]
enabled = true

# development (ローカル)
[env.development.vars]
CORS_ALLOW_ORIGINS = "http://localhost:5173"
AUTH_DOMAIN = "enchan.jp.auth0.com"
AUTH_AUDIENCE = "http://localhost:8787"

[[env.development.d1_databases]]
binding = "D1"
migrations_dir = "./src/migrations"
database_name = "financier-backend-db-development"
database_id = "00000000-0000-0000-0000-000000000000"

# staging
[env.staging.vars]
CORS_ALLOW_ORIGINS = "https://main.financier-frontend.pages.dev"
AUTH_DOMAIN = "enchan.jp.auth0.com"
AUTH_AUDIENCE = "https://stg.api.financier.enchan.me"

[[env.staging.routes]]
pattern = "stg.api.financier.enchan.me"
custom_domain = true

[[env.staging.d1_databases]]
binding = "D1"
migrations_dir = "./src/migrations"
database_name = "financier-backend-db-staging"
database_id = "939b406b-2cbe-40cd-8cda-496dc16e445d"

# Cloudflare
[env.production.vars]
CORS_ALLOW_ORIGINS = "https://financier.enchan.me"
AUTH_DOMAIN = "enchan.jp.auth0.com"
AUTH_AUDIENCE = "https://api.financier.enchan.me"

[[env.production.routes]]
pattern = "api.financier.enchan.me"
custom_domain = true

[[env.production.d1_databases]]
binding = "D1"
migrations_dir = "./src/migrations"
database_name = "financier-backend-db-production"
database_id = "4a850573-58bd-498d-a42b-57bbd5409625"
