import type { MockFinanceState } from './financier-model'

export const mockFinanceInitialState: MockFinanceState = {
  categories: [
    {
      id: 'cat-income-salary',
      name: '給与',
      type: 'income',
      status: 'active',
      isSavingCategory: false,
    },
    {
      id: 'cat-income-side',
      name: '副収入',
      type: 'income',
      status: 'active',
      isSavingCategory: false,
    },
    {
      id: 'cat-expense-housing',
      name: '住居費',
      type: 'expense',
      status: 'active',
      isSavingCategory: false,
    },
    {
      id: 'cat-expense-food',
      name: '食費',
      type: 'expense',
      status: 'active',
      isSavingCategory: false,
    },
    {
      id: 'cat-expense-transport',
      name: '交通費',
      type: 'expense',
      status: 'active',
      isSavingCategory: false,
    },
    {
      id: 'cat-expense-leisure',
      name: '娯楽費',
      type: 'expense',
      status: 'active',
      isSavingCategory: false,
    },
    {
      id: 'cat-expense-travel-saving',
      name: '旅行積立',
      type: 'expense',
      status: 'active',
      isSavingCategory: true,
    },
    {
      id: 'cat-expense-emergency-saving',
      name: '緊急積立',
      type: 'expense',
      status: 'active',
      isSavingCategory: true,
    },
    {
      id: 'cat-expense-archived',
      name: '旧サブスク',
      type: 'expense',
      status: 'archived',
      isSavingCategory: false,
    },
  ],
  fiscalYears: [
    { id: 'fy-2024', year: 2024, status: 'closed' },
    { id: 'fy-2025', year: 2025, status: 'active' },
  ],
  transactions: [
    {
      id: 'tx-001',
      type: 'income',
      amount: 320000,
      categoryId: 'cat-income-salary',
      transactionDate: '2025-12-25',
      eventId: 'evt-bonus-allocation',
      name: '12月給与',
      createdAt: '2025-12-25T09:00:00Z',
    },
    {
      id: 'tx-002',
      type: 'income',
      amount: 48000,
      categoryId: 'cat-income-side',
      transactionDate: '2026-01-12',
      name: 'フリーランス案件',
      createdAt: '2026-01-12T12:00:00Z',
    },
    {
      id: 'tx-003',
      type: 'expense',
      amount: 89000,
      categoryId: 'cat-expense-housing',
      transactionDate: '2026-01-30',
      name: '家賃',
      createdAt: '2026-01-30T08:00:00Z',
    },
    {
      id: 'tx-004',
      type: 'expense',
      amount: 32000,
      categoryId: 'cat-expense-food',
      transactionDate: '2026-02-02',
      name: '食料品と外食',
      createdAt: '2026-02-02T10:30:00Z',
    },
    {
      id: 'tx-005',
      type: 'expense',
      amount: 12000,
      categoryId: 'cat-expense-transport',
      transactionDate: '2026-02-06',
      name: '定期代',
      createdAt: '2026-02-06T07:45:00Z',
    },
    {
      id: 'tx-006',
      type: 'expense',
      amount: 30000,
      categoryId: 'cat-expense-travel-saving',
      transactionDate: '2026-02-08',
      eventId: 'evt-kanazawa-trip',
      name: '旅行積立の拠出',
      createdAt: '2026-02-08T20:00:00Z',
    },
    {
      id: 'tx-007',
      type: 'expense',
      amount: 25000,
      categoryId: 'cat-expense-emergency-saving',
      transactionDate: '2026-02-10',
      name: '緊急積立の拠出',
      createdAt: '2026-02-10T20:00:00Z',
    },
    {
      id: 'tx-008',
      type: 'expense',
      amount: 45000,
      categoryId: 'cat-expense-leisure',
      transactionDate: '2026-03-20',
      eventId: 'evt-kanazawa-trip',
      name: '未来日: 旅行予約金',
      createdAt: '2026-02-11T20:00:00Z',
    },
  ],
  budgets: [
    {
      fiscalYear: 2025,
      categoryId: 'cat-income-salary',
      budgetAmount: 3840000,
    },
    { fiscalYear: 2025, categoryId: 'cat-income-side', budgetAmount: 500000 },
    {
      fiscalYear: 2025,
      categoryId: 'cat-expense-housing',
      budgetAmount: 1080000,
    },
    { fiscalYear: 2025, categoryId: 'cat-expense-food', budgetAmount: 480000 },
    {
      fiscalYear: 2025,
      categoryId: 'cat-expense-transport',
      budgetAmount: 180000,
    },
    {
      fiscalYear: 2025,
      categoryId: 'cat-expense-leisure',
      budgetAmount: 360000,
    },
    {
      fiscalYear: 2025,
      categoryId: 'cat-expense-travel-saving',
      budgetAmount: 240000,
    },
    {
      fiscalYear: 2025,
      categoryId: 'cat-expense-emergency-saving',
      budgetAmount: 300000,
    },
  ],
  savingDefinitions: [
    {
      id: 'sav-001',
      categoryId: 'cat-expense-travel-saving',
      type: 'goal',
      targetAmount: 200000,
      deadline: '2026-08-31',
    },
    {
      id: 'sav-002',
      categoryId: 'cat-expense-emergency-saving',
      type: 'free',
    },
  ],
  savingWithdrawals: [
    {
      id: 'with-001',
      savingDefinitionId: 'sav-001',
      amount: 15000,
      withdrawalDate: '2026-01-31',
      memo: '新幹線チケット',
      createdAt: '2026-01-31T13:00:00Z',
    },
  ],
  events: [
    {
      id: 'evt-kanazawa-trip',
      name: '金沢旅行',
      startDate: '2026-03-20',
      endDate: '2026-03-23',
    },
    {
      id: 'evt-bonus-allocation',
      name: '2026年ボーナス配分',
      startDate: '2025-12-25',
      endDate: '2026-01-10',
    },
  ],
  eventTemplates: [
    {
      id: 'tpl-income-salary',
      name: '給与セット',
      defaultTransactions: [
        {
          categoryId: 'cat-income-salary',
          amount: 320000,
          name: '基本給',
        },
        {
          categoryId: 'cat-expense-transport',
          amount: 10000,
          name: '交通費精算',
        },
      ],
    },
    {
      id: 'tpl-trip',
      name: '旅行セット',
      defaultTransactions: [
        {
          categoryId: 'cat-expense-transport',
          amount: 18000,
          name: '交通',
        },
        {
          categoryId: 'cat-expense-leisure',
          amount: 25000,
          name: '観光・食事',
        },
      ],
    },
  ],
}
