/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransactionsIndexRouteImport } from './routes/transactions/index'
import { Route as SecretIndexRouteImport } from './routes/secret/index'
import { Route as SavingsIndexRouteImport } from './routes/savings/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as BudgetIndexRouteImport } from './routes/budget/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIndexRoute = TransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretIndexRoute = SecretIndexRouteImport.update({
  id: '/secret/',
  path: '/secret/',
  getParentRoute: () => rootRouteImport,
} as any)
const SavingsIndexRoute = SavingsIndexRouteImport.update({
  id: '/savings/',
  path: '/savings/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetIndexRoute = BudgetIndexRouteImport.update({
  id: '/budget/',
  path: '/budget/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about/': typeof AboutIndexRoute
  '/budget/': typeof BudgetIndexRoute
  '/events/': typeof EventsIndexRoute
  '/savings/': typeof SavingsIndexRoute
  '/secret/': typeof SecretIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutIndexRoute
  '/budget': typeof BudgetIndexRoute
  '/events': typeof EventsIndexRoute
  '/savings': typeof SavingsIndexRoute
  '/secret': typeof SecretIndexRoute
  '/transactions': typeof TransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about/': typeof AboutIndexRoute
  '/budget/': typeof BudgetIndexRoute
  '/events/': typeof EventsIndexRoute
  '/savings/': typeof SavingsIndexRoute
  '/secret/': typeof SecretIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about/'
    | '/budget/'
    | '/events/'
    | '/savings/'
    | '/secret/'
    | '/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/budget'
    | '/events'
    | '/savings'
    | '/secret'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/about/'
    | '/budget/'
    | '/events/'
    | '/savings/'
    | '/secret/'
    | '/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutIndexRoute: typeof AboutIndexRoute
  BudgetIndexRoute: typeof BudgetIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  SavingsIndexRoute: typeof SavingsIndexRoute
  SecretIndexRoute: typeof SecretIndexRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof TransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secret/': {
      id: '/secret/'
      path: '/secret'
      fullPath: '/secret/'
      preLoaderRoute: typeof SecretIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savings/': {
      id: '/savings/'
      path: '/savings'
      fullPath: '/savings/'
      preLoaderRoute: typeof SavingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget/': {
      id: '/budget/'
      path: '/budget'
      fullPath: '/budget/'
      preLoaderRoute: typeof BudgetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutIndexRoute: AboutIndexRoute,
  BudgetIndexRoute: BudgetIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  SavingsIndexRoute: SavingsIndexRoute,
  SecretIndexRoute: SecretIndexRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
