name: coverage difference on PR
on:
  pull_request:
    branches:
      - main

jobs:
  emit-coverage:
    outputs:
      summary: ${{ steps.emit.outputs.summary }}
    strategy:
      matrix:
        ref: ['main', '${{ github.head_ref }}']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.ref }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install
        run: npm i

      - name: generate coverage
        run: npm run -w backend test:coverage

      - name: emit coverage
        id: emit
        run: |
          summary=$( cat ./backend/coverage/coverage-summary.json | jq '.total' )
          echo "summary_${{ matrix.ref }}=$summary" >> "$GITHUB_OUTPUT"

  list:
    runs-on: ubuntu-latest
    needs: [emit-coverage]
    steps:
      - run: echo '${{ toJSON(needs.emit-coverage.outputs) }}'
