name: coverage difference on PR
on:
  pull_request:
    branches:
      - main

jobs:
  emit-coverage:
    outputs:
      summary_target: ${{ steps.emit.outputs.summary_target }}
      summary_source: ${{ steps.emit.outputs.summary_source }}
    strategy:
      matrix:
        ref: ['target', 'source']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{matrix.ref == 'target' && github.base_ref || github.head_ref }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install
        run: npm i

      - name: generate coverage
        run: npm run -w backend test:coverage

      - name: emit coverage
        id: emit
        run: |
          summary="$( cat ./backend/coverage/coverage-summary.json | jq -rc '.total' )"
          echo "summary_${{ matrix.ref }}=$summary" >> "$GITHUB_OUTPUT"
          echo ${{matrix.ref == 'target' && github.base_ref || github.head_ref }}

  list:
    runs-on: ubuntu-latest
    needs: [emit-coverage]
    steps:
      - run: echo '${{ toJSON(needs.emit-coverage.outputs) }}'
